import { defineConfig } from "vitepress";
import { VitePWA } from "vite-plugin-pwa";

import { read } from "./node_utils.js";
import { getJSONLD } from "./seo.js";

import { generateNav, locales } from "./navBar.js";
import { getFontCSS } from "./css.js";

const config = read("./pages/config.json");

export default defineConfig(async () => {
  const { preloads } = await getFontCSS(config.theme);
  return {
    head: [
      // Load google fonts
      ["link", { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "anonymous" }],
      ...preloads,
      // Manifest and icons
      ["link", { rel: "manifest", href: "/manifest.json" }],
      ["link", { rel: "icon", href: "/favicon.ico", type: "image/x-icon" }],
      ["script", { "data-goatcounter": config.dev?.goatcounter || "", async: true, src: "//gc.zgo.at/count.js" }],
    ],
    locales: locales(config.languages),
    title: config.title,
    cleanUrls: true,
    description: config.description,
    themeConfig: {
      nav: await generateNav(config),
      config: config,
    },
    sitemap: {
      hostname: config.dev?.siteurl,
    },
    async transformHead({ pageData }) {
      const path = pageData.relativePath
        .replace(/\.md$/, "")
        .replace(/\.html$/, "")
        .replace(/index$/, "");
      return getJSONLD(pageData.frontmatter, config, path);
    },
    vite: {
      plugins: [
        VitePWA({
          strategies: "injectManifest",
          // SW source file: docs/.vitepress/sw.js  (srcDir is relative to Vite root = docs/)
          srcDir: ".vitepress",
          filename: "sw.js",
          // The manifest is already generated by createFiles.js → docs/public/manifest.json
          manifest: false,
          // Show update banner (PWA.vue uses useRegisterSW to detect the needRefresh signal)
          registerType: "prompt",
          devOptions: { enabled: false },
          injectManifest: {
            // Precache built JS/CSS/HTML and common static assets
            globPatterns: ["**/*.{js,css,html,png,svg,ico,woff2,woff}"],
            maximumFileSizeToCacheInBytes: 4000000,
          },
        }),
      ],
    },
  };
});
